### ISSUE TITLE
Problem Retrieve API Documentation

### ISSUE THREAD

**Issue by Captain-X** [function-x/Orange-Juice#14]
为 lib/problem_retrieve.js 添加 jsdoc 与 apidoc 代码文档。

**Comment by zccz14** [comment]
#24 Merged

**Comment by zccz14** [comment]
由 @wtupc96 @zccz14 共同完成

修改了API 的内涵

Problem Retrieve：在题库中检索属于该用户的题目，支持`title`, `description` 的全文检索
