### ISSUE TITLE
软件项目管理最终文档分配

### ISSUE THREAD

**Issue by zccz14** [function-x/Orange-Juice#34]
根据要求我们需要准备如下文档：

- [x] 项目章程
- [x] 项目管理计划
- [x] 软件需求说明书
- [x] 概要设计说明书
- [x] 数据库设计说明书
- [x] 详细设计说明书
- [x] 测试计划
- [x] 源代码
- [x] 测试结果报告
- [x] 项目组总结报告
- [x] 个人项目工作总结

**Comment by zccz14** [comment]
**项目组总结报告**由我完成，其余人各至少完成一份 **个人项目工作总结**

**Comment by zccz14** [comment]
**软件需求说明书**与**测试结果报告**由 @helenCao 完成

**Comment by zccz14** [comment]
**测试计划**由 @wtupc96 完成

**Comment by Thrimbda** [comment]
我领**数据库设计说明书**

**Comment by zccz14** [comment]
请 @Captain-X 对以下项目分别建立 Issue 来进行进度追踪。

- 软件需求说明书
- 概要设计说明书
- 数据库设计说明书
- 详细设计说明书
- 测试计划
- 测试结果报告

**Comment by zccz14** [comment]
**概要设计说明**可以参考本项目的[Wiki](https://github.com/function-x/Orange-Juice/wiki)

**Comment by Captain-X** [comment]
我领概要设计说明书

**Comment by zccz14** [comment]
那么 @ddhee 做 **详细设计说明书**

**Comment by zccz14** [comment]
完成了所有任务的分配
