### ISSUE TITLE
[DOC]软件需求说明书

### ISSUE THREAD

**Issue by Captain-X** [function-x/Orange-Juice#36]
及时报告文档书写进度

**Comment by helenCao** [comment]
[软件需求说明书（GB856T-88）.pdf](https://github.com/function-x/Orange-Juice/files/673749/GB856T-88.pdf)

**Comment by Captain-X** [comment]
1.2 删去“说明：”    ？
1.4 删去“列出用得着的参考资料，如：”      明显是填写提示性语句

**Comment by helenCao** [comment]
[软件需求说明书（GB856T-88）.pdf](https://github.com/function-x/Orange-Juice/files/673795/GB856T-88.pdf)

**Comment by helenCao** [comment]
[软件需求说明书（GB856T-88）.pdf](https://github.com/function-x/Orange-Juice/files/674389/GB856T-88.pdf)

**Comment by zccz14** [comment]
@Captain-X review
