### ISSUE TITLE
[DOC]测试结果报告

### ISSUE THREAD

**Issue by Captain-X** [function-x/Orange-Juice#37]
及时报告文档书写进度

**Comment by helenCao** [comment]
[测试分析报告（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674332/GB8567-88.pdf)

**Comment by helenCao** [comment]
[测试分析报告（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674390/GB8567-88.pdf)

**Comment by zccz14** [comment]
@Captain-X review
