### ISSUE TITLE
[DOC]测试计划

### ISSUE THREAD

**Issue by Captain-X** [function-x/Orange-Juice#38]
及时报告文档书写进度

**Comment by wtupc96** [comment]
[测试计划（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674175/GB8567-88.pdf)

**Comment by Mixresque** [comment]
1.2中”在进行测试之前，本组项目开发人员已经开发完成了 Online Judge 项目“有没有问题？

**Comment by zccz14** [comment]
我们的项目叫 Orange Juice，XJTU Online Judge 是后续的项目。

**Comment by zccz14** [comment]
2.3.4 工作流程/。 这里这个斜杠应该去掉

**Comment by helenCao** [comment]
我们不是项目组叫Orange Juice 项目叫XJTU Online Judge吗 @zccz14

**Comment by zccz14** [comment]
@helenCao 是这样的，如果是 XJTU Online Judge 的话我们做不完了，现在只缩小到其中的API Server，名为 Orange Juice

**Comment by Captain-X** [comment]
1,1 Function 小写

**Comment by Captain-X** [comment]
1.4 加作者和时间

**Comment by wtupc96** [comment]
[测试计划（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674209/GB8567-88.pdf)

**Comment by wtupc96** [comment]
[测试计划（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674212/GB8567-88.pdf)

**Comment by helenCao** [comment]
用户创建第6种情况没有测试原因 用户组名称更新没有更新失败的情况

**Comment by wtupc96** [comment]
[测试计划（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674324/GB8567-88.pdf)
