### ISSUE TITLE
[DOC]数据库设计说明书

### ISSUE THREAD

**Issue by Captain-X** [function-x/Orange-Juice#39]
及时报告文档书写进度

**Comment by Thrimbda** [comment]
[数据库设计说明书（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674450/GB8567-88.pdf)

**Comment by zccz14** [comment]
@Captain-X review

**Comment by zccz14** [comment]
1.4 要加作者与时间

**Comment by Thrimbda** [comment]
got，顺带有关用户组相关数据表设计都不要了对吗

**Comment by zccz14** [comment]
对的，暂时都不要写了

**Comment by Thrimbda** [comment]
[Orange-Juice数据库设计说明书.pdf](https://github.com/function-x/Orange-Juice/files/674498/Orange-Juice.pdf)
@Captain-X review

**Comment by Thrimbda** [comment]
@zccz14 应该没问题了？

**Comment by zccz14** [comment]
@Macsnow14 对，辛苦你了
