### ISSUE TITLE
[DOC]概要设计说明书

### ISSUE THREAD

**Issue by Captain-X** [function-x/Orange-Juice#40]
- [x] 引言
- [x] 总体设计
- [x] 接口设计
- [x] 运行设计
- [x] 系统数据结构设计
- [x] 系统出错处理设计

**Comment by Captain-X** [comment]
1.引言
2.总体设计
3.接口设计
4.运行设计
5.系统数据结构设计
6.系统出错处理设计

**Comment by zccz14** [comment]
写了这么多了？

**Comment by Captain-X** [comment]
引言done

**Comment by Captain-X** [comment]
运行时间是什么

**Comment by zccz14** [comment]
I'm confused too.

**Comment by Captain-X** [comment]
说明每种运行模块组合将占用各种资源的时间。

**Comment by zccz14** [comment]
知らない

**Comment by Captain-X** [comment]
运行模块大概就是只相关的一系列操作，比如创建题单这种

**Comment by zccz14** [comment]
时间以什么单位度量？

**Comment by Captain-X** [comment]
没说

**Comment by zccz14** [comment]
要不别写这个了

**Comment by Captain-X** [comment]
dalao要我不写了，我就不写了

**Comment by Captain-X** [comment]
[概要设计说明书（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674444/GB8567-88.pdf)

**Comment by Captain-X** [comment]
概要设计说明书1.0 done

**Comment by zccz14** [comment]
@ddhee

**Comment by Captain-X** [comment]
[概要设计说明书（GB8567-88） .pdf](https://github.com/function-x/Orange-Juice/files/674455/GB8567-88.pdf)

**Comment by zccz14** [comment]
ha
