### ISSUE TITLE
[DOC]详细设计说明书

### ISSUE THREAD

**Issue by Captain-X** [function-x/Orange-Juice#41]
及时报告文档书写进度

**Comment by zccz14** [comment]
负责人： @ddhee 
协作者： @aak1247 

请协调好工作。

**Comment by aak1247** [comment]
get

**Comment by aak1247** [comment]
完成1、2两个部分的编写，模块部分进行大约一半

**Comment by zccz14** [comment]
@aak1247 你跟 @ddhee 协调过工作吗？

**Comment by aak1247** [comment]
@zccz14 协调过，正在协同工作中。

**Comment by zccz14** [comment]
好的加油 👍

**Comment by Mixresque** [comment]
完成引言、程序系统的结构、用户模块设计说明

**Comment by zccz14** [comment]
我更新了文档不知道对你们有没有帮助

**Comment by zccz14** [comment]
[docs.zip](https://github.com/function-x/Orange-Juice/files/674646/docs.zip)
这是新Build的文档

**Comment by aak1247** [comment]
这是目前的状态
[详细设计说明书（GB8567-88）.pdf](https://github.com/function-x/Orange-Juice/files/674731/GB8567-88.pdf)

**Comment by aak1247** [comment]
现在的题单不都是公开的吗，没有群组的话这个看题单的时候还要判权限吗

**Comment by aak1247** [comment]
假定是最终版
[详细设计说明书（GB8567-88） .pdf](https://github.com/function-x/Orange-Juice/files/674790/GB8567-88.pdf)

**Comment by aak1247** [comment]
最终版
[详细设计说明书.pdf](https://github.com/function-x/Orange-Juice/files/675046/default.pdf)

**Comment by Captain-X** [comment]
1.3 后面的不要分行？

**Comment by aak1247** [comment]
不知道==你觉得分好就分吧 我都不知道那是什么意思...

**Comment by aak1247** [comment]
还有别的问题吗快check一下

**Comment by zccz14** [comment]
没有了吧

**Comment by aak1247** [comment]
最终文档
[详细设计说明书.pdf](https://github.com/function-x/Orange-Juice/files/675057/default.pdf)
