### ISSUE TITLE
[DOC] 项目组总结报告

### ISSUE THREAD

**Issue by zccz14** [function-x/Orange-Juice#42]
由项目经理负责完成。

- [x] 项目任务分工与绩效报告
- [x] 任务完成情况
- [x] 项目经理对项目组成员的评价
- [x] 项目成败分析

**Comment by zccz14** [comment]
ShareLaTeX URL: https://www.sharelatex.com/project/58620cf969f45ebb466f437c

**Comment by zccz14** [comment]
完成项目任务分工部分的编写

**Comment by zccz14** [comment]
完成任务完成情况部分的编写

**Comment by zccz14** [comment]
完成**项目组成员评价**

**Comment by zccz14** [comment]
[项目组总结报告.pdf](https://github.com/function-x/Orange-Juice/files/674503/default.pdf)

**Comment by Captain-X** [comment]
在本项目的前期表现得比较困惑？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
