### ISSUE TITLE
在提交公共题单中题目时出现 “API错误1“

### ISSUE THREAD

**Issue by Thrimbda** [function-x/Orange-Juice#43]
经测试在登录状态下公共题单列表中任一题单题目提交时都会出现，会不会是我这个用户有问题？
用户名`macsnow`

**Comment by zccz14** [comment]
你重新注册一个用户有没有问题？

**Comment by Thrimbda** [comment]
新注册没问题，我重新登录以后也没问题了，那应该就是登录失效？

**Comment by zccz14** [comment]
我刚刚尝试修复了这个BUG 8b3fc9b
