### ISSUE TITLE
User Logout API Documentation

### ISSUE THREAD

**Issue by zccz14** [function-x/Orange-Juice#9]
为 `lib/user_logout.js` 添加 jsdoc 与 apidoc 代码文档。

**Comment by wtupc96** [comment]
test

**Comment by zccz14** [comment]
看一下 `lib/user_create.js` 里面的被

```js
/** */
```

包围的部分，那部分会被识别为代码文档，要按照规定的格式写。

具体可查询 jsdoc 与 apidoc 的官方文档。

**Comment by zccz14** [comment]
+ [apidoc 文档](http://apidocjs.com/)
+ [jsdoc 文档](http://usejsdoc.org/)
+ [jsdoc 中文文档](http://www.css88.com/doc/jsdoc/index.html)

**Comment by zccz14** [comment]
well done by @wtupc96
